### ISSUE TITLE
KituraSys: no such module 'Dispatch'

### ISSUE THREAD

**Issue by joaoamaral** [joaoamaral/KituraHeroku#1]
Using DEVELOPMENT-SNAPSHOT-2016-03-24-a and https://github.com/kylef/heroku-buildpack-swift.git buildpack

but I found this error about Dispatch module while compiling KituraSys
can someone give me some help? Thank you :)

```
remote: Compiling KituraSysno such module 'Dispatch'
remote: /tmp/build_daf57757ad8192bb59b6c59bc2bc27a3/Packages/Kitura-Sys-0.7.0/Sources/KituraSys/SysUtils.swift:17:8: error: no such module 'Dispatch'
remote: import Dispatch
remote:        ^
remote: 
<unknown>:0: error: build had 1 command failures
remote: swift-build: error: exit(1): /app/tmp/cache/swiftenv/versions/DEVELOPMENT-SNAPSHOT-2016-03-24-a/usr/bin/swift-build-tool -f /tmp/build_daf57757ad8192bb59b6c59bc2bc27a3/.build/release.yaml default
```

**Comment by FWMatt** [comment]
👍 

I have the same issue. Despite building correctly on my locale machine the heroku-swift-buildpack doesnt compile the App correctly on Heroku. Any thoughts?

Nice work btw :)
